---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - testment.harvey.io
  resources:
  - testments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testment.harvey.io
  resources:
  - testments/finalizers
  verbs:
  - update
- apiGroups:
  - testment.harvey.io
  resources:
  - testments/status
  verbs:
  - get
  - patch
  - update
