# permissions for end users to view testments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testment-viewer-role
rules:
- apiGroups:
  - testment.harvey.io
  resources:
  - testments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testment.harvey.io
  resources:
  - testments/status
  verbs:
  - get
